# @package _global_

cristal:
  _target_: src.environments.cristal.make_environment
  discrete: false
  render_mode: null
  max_steps: 750

straight:
  _target_: src.environments.straight.make_environment
  discrete: false
  render_mode: null
  max_steps: 750
