_target_: src.environments.cristal.make_environment
discrete: ???
wrappers:
  - "WithRoadInfo"
  - "WithBaseInfo"
  - "WithPathInfo"
  - "WithObstaclesInfo"
random_obstacles: true
number_of_obstacles: 2
random_spawn: true
render_mode: null
dimensions: [80.0, 40.0]

# python train.py --multirun environment=cristal environment.discrete=true environment.wrappers=\[WithBaseInfo,WithPathInfo,WithObstaclesInfo\],\[WithRoadInfo,WithBaseInfo,WithPathInfo,WithObstaclesInfo\] controller=dqn,ppo-discrete,trpo-discrete reward=path-progress,simple
