_target_: src.environments.straight.make_environment
discrete: ???
render_mode: null
target_velocity: 1.5
n_steering: 15
min_obstacles: 3
max_obstacles: 4
min_radius: 0.6
max_radius: 1.2
lateral_range: 2.5
min_x_spacing: 8.0
min_passage_width: 2.5
max_steps: 600
