_target_: src.controllers.trpo.TRPOController
model_kwargs:
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  ent_coef: 0.01 # encourage exploration of all 9 actions
  verbose: 1
