total_timesteps: 1_000_000
seed: 984 # 478
wrappers:
  - with_path_info
  - with_obstacles_info
  - with_base_info
  - with_road_info
  - random_obstacles

defaults:
  - controller: ???
  - environment@train: ???
  - environment@eval: ???
  - reward: ???
  - defaults
  - _self_
